baseURL = "https://www.example.org/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Ayush"
    author = "Darshan Baral"
    description = "Website title"
    copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Ayush"
		tagline = "homosapien"
		location = "Gaya, India"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/ayush-mishra-62586b190"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-stack-overflow"
            url = "https://stackoverflow.com/users/12734102/ayush-mishra"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/ayush-AI"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/supermanaayush?s=09"
            title = "Twitter"
		[[params.social.list]]
            class = "fab"
            icon = "fa-instagram"
            url = "https://www.instagram.com/_ayush.mishra__/"
            title = "Instagram"
		

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**A kid who is addicted to learning.** I am currently studying BTech in ECE from Netaji Subash Engineering College, kolkata, India. "

    

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "+2 in PCM"
            college = "Gaya College Gaya"
            dates = "2015 - 2017"
           
        [[params.education.list]]
            degree = "Matric"
            college = "D.A.V Public School Medical Unit, Gaya"
        
        

    # Publication section
    [params.publication]
        title = "Blogs"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Robotics"]

        [[params.publication.list]]
            title = "Introduction to Ardudino"
            authors = "Ayush"
            date = "2020"
            journal = "Its a blog for getting you started with the arduino"
            link = "https://tech-a-way.vercel.app/arduino_basics.html"
            type = "Robotics"

        
    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Blogging Website"
            url = "https://tech-a-way.vercel.app/index.html"
            description = "Its our personal website for sharing our knowledge."
        [[params.project.list]]
            title = "Line following robot"
            url = "#"
            description = "Robot which follows the black line sensing it using IR array sensor. We used arduino as a microcontroller and l293D motor driver for controling the speed of the motor."
        

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Html, CSS"
            skillrating = 90
        [[params.skill.list]]
            skill = "JavaScript"
            skillrating = 80
        [[params.skill.list]]
            skill = "C"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Gaming"
        [[params.hobby.list]]		
		    hobby = "Writing"
        [[params.hobby.list]]		
		    hobby = "Reading"
